name: manual jobs

on:
  workflow_dispatch:
    inputs:
        environment:
            description: demo
            required: true
            type: string
            default: "dev"

   value:
    descirption: demo
    required: true
    type: number
    default: 1000

   allow-run:
    description: allow to run steps
    required: true
    type: boolean
    default: true
    
   data_env:
    description: allow to run steps
    required: true
    type: choice
    options:
        -dev
        -stg
        -prod
        -init
        
jobs:
    demo_input:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo branch
              uses: actions/checkout@v7

            - name: print values inputs
              run: |
               echo "env:${{github.event.inputs.environment}}"

            - name: allow-run true
              if: github.events.inputs.allow-run
              run:
                echo "build started"

            - name: demo choice inputs
              run: |
                echo "${{github.events.inputs.data_env}}"
                echo "${{github.events.inputs.value}}"
