name: manual jobs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: demo
        required: true
        type: string
        default: "dev"

      value:
        description: demo
        required: true
        type: number
        default: 1000

      allow-run:
        description: allow to run steps
        required: true
        type: boolean
        default: true

      data_env:
        description: allow to run steps
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod
          - init

jobs:
  demo_input:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo branch
        uses: actions/checkout@v4

      - name: Print values inputs
        run: |
          echo "env: ${{ github.event.inputs.environment }}"
          echo "value: ${{ github.event.inputs.value }}"
          echo "data_env: ${{ github.event.inputs.data_env }}"

      - name: Allow-run true
        if: ${{ github.event.inputs.allow-run == 'true' }}
        run: |
          echo "Build started"

      - name: Demo choice inputs
        run: |
          echo "${{ github.event.inputs.data_env }}"
          echo "${{ github.event.inputs.value }}"
